network:
  auto_run_on_connect: true
  default_plugins:
  - ip_info
  - ping_test
  interface: eth0
  poll_interval: 5
  wifi_interface: wlan0
plugins:
  arp_scan:
    enabled: true
  ip_info:
    enabled: true
    targets:
    - gateway
    - 8.8.8.8
    - 1.1.1.1
  packet_capture:
    count: 100
    enabled: true
    filter: ''
  ping_test:
    count: 4
    enabled: true
    targets:
    - gateway
    - 8.8.8.8
    - 1.1.1.1
  port_scan:
    enabled: true
    ports: common
    targets:
    - gateway
  speedtest:
    enabled: true
    server: null
  traceroute:
    enabled: true
    targets:
    - 8.8.8.8
    - 1.1.1.1
  vlan_detector:
    enabled: true
security:
  allow_eth0_access: false
  jwt_secret: 4e13e06154c59202fa5583db5416b227e9ecabc884d9c17aeb45ef743214e1d7
  password_hash: null
  rate_limit: 60
setup:
  completed: false
system:
  data_dir: /home/anoam/NetScout-Pi/data
  debug: true
  log_dir: /home/anoam/NetScout-Pi/logs
  log_level: DEBUG
  plugin_dir: /home/anoam/NetScout-Pi/config/plugins
web:
  auth_required: false
  cookie_secure: true
  host: 0.0.0.0
  log_requests: true
  port: 8081
  session_timeout: 3600
